// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: NumsReducerService.proto

package org.egdev.reducer;

public interface NumbersRespOrBuilder extends
    // @@protoc_insertion_point(interface_extends:org.egdev.NumbersResp)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>double result = 1;</code>
   */
  double getResult();

  /**
   * <code>string operation = 2;</code>
   */
  String getOperation();
  /**
   * <code>string operation = 2;</code>
   */
  com.google.protobuf.ByteString
      getOperationBytes();
}
