// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: NumsReducerService.proto

package org.egdev.reducer;

public interface NumbersReqOrBuilder extends
    // @@protoc_insertion_point(interface_extends:org.egdev.NumbersReq)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated double numbers = 1;</code>
   */
  java.util.List<Double> getNumbersList();
  /**
   * <code>repeated double numbers = 1;</code>
   */
  int getNumbersCount();
  /**
   * <code>repeated double numbers = 1;</code>
   */
  double getNumbers(int index);
}
