// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: NumsReducerService.proto

package org.egdev.reducer;

public final class NumsReducerServiceOuterClass {
  private NumsReducerServiceOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_egdev_NumbersReq_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_egdev_NumbersReq_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_egdev_NumbersResp_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_egdev_NumbersResp_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\030NumsReducerService.proto\022\torg.egdev\"\035\n" +
      "\nNumbersReq\022\017\n\007numbers\030\001 \003(\001\"0\n\013NumbersR" +
      "esp\022\016\n\006result\030\001 \001(\001\022\021\n\toperation\030\002 \001(\t2J" +
      "\n\022NumsReducerService\0224\n\003avg\022\025.org.egdev." +
      "NumbersReq\032\026.org.egdev.NumbersRespB\r\n\tor" +
      "g.egdevP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_org_egdev_NumbersReq_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_org_egdev_NumbersReq_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_egdev_NumbersReq_descriptor,
        new String[] { "Numbers", });
    internal_static_org_egdev_NumbersResp_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_org_egdev_NumbersResp_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_egdev_NumbersResp_descriptor,
        new String[] { "Result", "Operation", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
