// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: FileUploadService.proto

package org.egdev.fileUpload;

public interface FileUploadReqOrBuilder extends
    // @@protoc_insertion_point(interface_extends:org.egdev.FileUploadReq)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string name = 1;</code>
   */
  String getName();
  /**
   * <code>string name = 1;</code>
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>bytes content = 2;</code>
   */
  com.google.protobuf.ByteString getContent();

  /**
   * <code>int64 offset = 3;</code>
   */
  long getOffset();
}
