// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: FileUploadService.proto

package org.egdev.fileUpload;

public interface FileUploadRespOrBuilder extends
    // @@protoc_insertion_point(interface_extends:org.egdev.FileUploadResp)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool okStatus = 1;</code>
   */
  boolean getOkStatus();

  /**
   * <code>string message = 2;</code>
   */
  String getMessage();
  /**
   * <code>string message = 2;</code>
   */
  com.google.protobuf.ByteString
      getMessageBytes();
}
