// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: FileUploadService.proto

package org.egdev.fileUpload;

public final class FileUploadServiceOuterClass {
  private FileUploadServiceOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_egdev_FileUploadReq_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_egdev_FileUploadReq_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_egdev_FileUploadResp_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_egdev_FileUploadResp_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\027FileUploadService.proto\022\torg.egdev\">\n\r" +
      "FileUploadReq\022\014\n\004name\030\001 \001(\t\022\017\n\007content\030\002" +
      " \001(\014\022\016\n\006offset\030\003 \001(\003\"3\n\016FileUploadResp\022\020" +
      "\n\010okStatus\030\001 \001(\010\022\017\n\007message\030\002 \001(\t2X\n\021Fil" +
      "eUploadService\022C\n\nuploadFile\022\030.org.egdev" +
      ".FileUploadReq\032\031.org.egdev.FileUploadRes" +
      "p(\001B\r\n\torg.egdevP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_org_egdev_FileUploadReq_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_org_egdev_FileUploadReq_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_egdev_FileUploadReq_descriptor,
        new String[] { "Name", "Content", "Offset", });
    internal_static_org_egdev_FileUploadResp_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_org_egdev_FileUploadResp_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_egdev_FileUploadResp_descriptor,
        new String[] { "OkStatus", "Message", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
